### ISSUE TITLE
TZ for each task

### ISSUE THREAD

**Issue by pchaganti** [treasure-data/perfectsched#3]
This looks very interesting. Is it possible to run each task with a different TZ or does a task use the default TZ specified in the configuration?

thanks!

**Comment by pchaganti** [comment]
Looking at the specs, it seems like each task can use its own TZ. Am i reading this right?

```Ruby
sc.add('sched01', 't01', {:cron=>'* * * * *', :timezone=>'UTC'})
```

**Comment by nurse** [comment]
Yeah as it shows.

**Comment by pchaganti** [comment]
Perfect!
